name: Build Flutter Web App

on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_path: ${{ steps.build.outputs.build_path }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env File
        run: |
          echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
          echo MY_PERSONAL_EMAIL=${{ secrets.MY_PERSONAL_EMAIL }} >> .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> .env
          echo FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
          echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> .env
          echo FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
          echo FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} >> .env
          echo FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
          echo FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} >> .env
          echo FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }} >> .env
          echo FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }} >> .env
          echo FIREBASE_IOS_API_KEY=${{ secrets.FIREBASE_IOS_API_KEY }} >> .env
          echo FIREBASE_IOS_APP_ID=${{ secrets.FIREBASE_IOS_APP_ID }} >> .env
          echo FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }} >> .env

      - name: Build Flutter Web
        id: build
        run: |
          flutter build web --release
          echo "build_path=$(pwd)/build/web" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web
          retention-days: 1  # Set to minimum required time
