name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_call: {}
  # push:
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Create dotenv File
        run: |
          echo EMAILJS_PUBLIC_KEY=${{ secrets.EMAILJS_PUBLIC_KEY }} >> dotenv
          echo EMAILJS_PRIVATE_KEY=${{ secrets.EMAILJS_PRIVATE_KEY }} >> dotenv
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} >> dotenv
          echo FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} >> dotenv
          echo FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> dotenv
          echo FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> dotenv
          echo FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} >> dotenv
          echo FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> dotenv
          echo FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} >> dotenv
          echo FIREBASE_ANDROID_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }} >> dotenv
          echo FIREBASE_ANDROID_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }} >> dotenv
          echo FIREBASE_IOS_API_KEY=${{ secrets.FIREBASE_IOS_API_KEY }} >> dotenv
          echo FIREBASE_IOS_APP_ID=${{ secrets.FIREBASE_IOS_APP_ID }} >> dotenv
          echo FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }} >> dotenv

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        id: build
        run: |
              flutter build web --release \
              --dart-define=EMAILJS_PUBLIC_KEY=${{ secrets.EMAILJS_PUBLIC_KEY }} \
              --dart-define=EMAILJS_PRIVATE_KEY=${{ secrets.EMAILJS_PRIVATE_KEY }} \
              --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
              --dart-define=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
              --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
              --dart-define=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
              --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
              --dart-define=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
              --dart-define=FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Update base href for GitHub Pages
        run: |
          sed -i 's|<base href="/">|<base href="/My_Portfolio/">|g' build/web/index.html

      - name: Create .gitignore in build/web
        run: echo "assets/dotenv" >> build/web/.gitignore

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
