name: Deploy to Firebase

on:
  workflow_dispatch:
  workflow_call: {}
  # push:
  #   branches:
  #     - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}

  cleanup:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Delete workflow artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: web-build
